### PR TITLE
Added measure tool "center-to-center distance"

### PR DESCRIPTION
**Pull request by neuoy**
Same as "Min distance", but measures between centers of each selected shape. This is useful to measure distance between circles.

I have renamed MeasureMinDistance as MeasureDistance, and MeasureDisplayMinDistance as MeasureDisplayDistance, since I now use them in a more generic manner. And added a new item in the dropdown which maps to MeasureType::CenterDistance.

screenshot

### CODE REVIEW

**Comment by HuguesDelorme** [comment]
That's a great contribution!

**Comment by HuguesDelorme** [comment]
@neuoy
Unfortunately after the merge of your PR you don't appear in the list of contributors.
That's a pity.
Could you please have a look to this [GitHub doc page](https://docs.github.com/en/free-pro-team@latest/github/visualizing-repository-data-with-graphs/viewing-a-projects-contributors#troubleshooting-contributors)
I suspect "_The email address you used to author the commits isn't connected to your account on GitHub_" could be the cause.

**Comment by neuoy** [comment]
Thanks for the merge! I've updated my email settings, should be all set now. FYI, I'm also working on other small features (filtering the objects list with a search field, and a "turn table" camera mode), since I think this is a bit lacking for our usage : a viewer for the vheliotech 3D files https://git.vhelio.org/vhelio/vheliotech-freecad/wiki/Visionnage-des-fichiers-3D-avec-Mayo . Mayo is great for this : very simple for non-computer-expert persons, and also very efficient on old computers. Thanks for this great tool!

**Comment by HuguesDelorme** [comment]
@neuoy
You still don't appear in the contributor list, I guess you will be included with your next PR!
Nice community project(vheliotech), glad to see Mayo can help

**Pull request merged**
